name: Bun CI

on: push

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
        working-directory: backend
      - run: bun run dev
        working-directory: backend

#   frontend:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: oven-sh/setup-bun@v1
#       - run: bun install
#         working-directory: frontend
#       - run: bun run build
#         working-directory: frontend